# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Publishing-using-gradle

name: publish

on:
  release:
    types: [ created ]

jobs:
  build:
    strategy:
      matrix:
        # Use these Java versions
        java: [ 17 ]
        # and run on Linux, Windows and MacOS
        os: [ ubuntu-20.04, windows-latest, macos-11 ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout repository
        uses: actions/checkout@v3
      - name: validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: setup jdk ${{ matrix.java }}
        uses: actions/setup-java@v2.3.1
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.java }}
      - name: make gradle wrapper executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew
      - name: Publish to GitHub Packages  (Linux)
        if: ${{ runner.os == 'Linux' }}
        run: gradle publish
        env:
          MCD_USERNAME: ${{ secrets.MCD_USERNAME }}
          MCD_PASSWORD: ${{ secrets.MCD_PASSWORD }}
      - name: Publish to GitHub Packages  (Windows)
        if: ${{ runner.os == 'Windows' }}
        run: gradle publishMingwX64PublicationToMavenRepository
        env:
          MCD_USERNAME: ${{ secrets.MCD_USERNAME }}
          MCD_PASSWORD: ${{ secrets.MCD_PASSWORD }}
      - name: Publish to GitHub Packages  (macOS)
        if: ${{ runner.os == 'macOS' }}
        run: gradle publishMacosX64PublicationToMavenRepository
        env:
          MCD_USERNAME: ${{ secrets.MCD_USERNAME }}
          MCD_PASSWORD: ${{ secrets.MCD_PASSWORD }}
